### ISSUE TITLE
could not mount SMB share in 1.20

### ISSUE THREAD

**Issue by woloss** [kubernetes-csi/csi-driver-smb#176] opened 2020-12-18 09:25 UTC
Due to my own mistake, I updated cluster to 1.20.0 version (luckily it's not production)

Now I can't mount SMB share and face such issue:
`Warning  FailedMount   106s (x11 over 7m57s)  kubelet          MountVolume.NewMounter initialization failed for volume "pvc-1231231" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string `

I tried to add those lines to DaemonSet/CSIDriver:
`fsGroupChangePolicy: None  fsGroupPolicy: None`
Didn't work out either.

So, any quick fix solutions before next release of driver?

**Environment**:
- CSI Driver version: 0.5.0
- Kubernetes version (use `kubectl version`): 1.20.0
- OS (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS

**Comment by andyzhangx** [comment] 2020-12-19 13:52
would you add `fsGroupPolicy: None` in `csi-smb-driver.yaml` in 1.20 cluster, and try again? thanks.
```
~/go/src/github.com/kubernetes-csi/csi-driver-smb# git diff
diff --git a/deploy/csi-smb-driver.yaml b/deploy/csi-smb-driver.yaml
index 1ffbb9f..6c1419e 100644
--- a/deploy/csi-smb-driver.yaml
+++ b/deploy/csi-smb-driver.yaml
@@ -6,3 +6,4 @@ metadata:
 spec:
   attachRequired: false
   podInfoOnMount: true
+  fsGroupPolicy: None
```

This change looks like a breaking change started from 1.20, we don't want to add `fsGroupPolicy: None` now since it would break in k8s version < 1.20, while from 1.20, we have to add `fsGroupPolicy: None`, I think this is incorrect, `fsGroupPolicy` should default to `None` in 1.20, that would not break the setting. Pls try above setting first, thanks.

**Comment by woloss** [comment] 2020-12-19 17:29
Sadly I already gone back to 1.19.4, because another CSI like Rook Ceph not working as well :(

I'm sure that tried "fsGroupPolicy: None" in csi-smb-driver.yaml, even fully deleted, and recreated driver deploy. Maybe I needed to fully clean CSI driver.

If I'll have spare time soon, I'll make 1.20.0 again and test again.

**Comment by andyzhangx** [comment] 2020-12-20 11:50
smb mount works on my k8s 1.20 cluster:

```console
azureuser@k8s-master-16965074-0:~$ k exec -it statefulset-smb-0 sh
# df -h
Filesystem                                    Size  Used Avail Use% Mounted on
overlay                                        29G   11G   19G  38% /
tmpfs                                          64M     0   64M   0% /dev
tmpfs                                         3.4G     0  3.4G   0% /sys/fs/cgroup
//smb-server.default.svc.cluster.local/share   29G   12G   18G  39% /mnt/smb
/dev/sda1                                      29G   11G   19G  38% /etc/hosts
shm                                            64M     0   64M   0% /dev/shm
tmpfs                                         3.4G   12K  3.4G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                         3.4G     0  3.4G   0% /proc/acpi
tmpfs                                         3.4G     0  3.4G   0% /proc/scsi
tmpfs                                         3.4G     0  3.4G   0% /sys/firmware
# exit
azureuser@k8s-master-16965074-0:~$ k get no -o wide
NAME                                STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-agentpool-16965074-vmss000000   Ready    agent    5d22h   v1.20.0   10.240.0.4     <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   docker://19.3.12
k8s-agentpool-16965074-vmss000001   Ready    agent    5d22h   v1.20.0   10.240.0.35    <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   docker://19.3.12
k8s-agentpool-16965074-vmss000002   Ready    agent    4d21h   v1.20.0   10.240.0.96    <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   docker://19.3.12
k8s-master-16965074-0               Ready    master   5d22h   v1.20.0   10.255.255.5   <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   docker://19.3.12
```

**Comment by woloss** [comment] 2020-12-20 13:10
Interesting. Deployed 1.20.1 from scratch, smb mount works w/o issues. Same deploy.yaml, except the fact that didn't install drivers for Rook yet.

I guess either I had some weird update, or something related to Rook caused issues for other CSI drivers.

**Comment by jmarcedwards** [comment] 2020-12-21 20:27
So, I'm running into the same issue, but it not directly related to "SMB" (I'm assuming Samba).

`Events:                                                                                                                                                                                 │
│   Type     Reason       Age                  From                           Message                                                                                                     │
│   ----     ------       ----                 ----                           -------                                                                                                     │
│   Warning  FailedMount  30m (x15 over 74m)   kubelet, rhel77-combo1-clstr2  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[wo │
│ dpress-persistent-storage default-token-ptmfc[]: timed out waiting for the condition                                                                                                    │
│   Warning  FailedMount  5m59s (x9 over 67m)  kubelet, rhel77-combo1-clstr2  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[de │
│ ault-token-ptmfc wordpress-persistent-storage[]: timed out waiting for the condition                                                                                                    │
│   Warning  FailedMount  46s (x45 over 76m)   kubelet, rhel77-combo1-clstr2  MountVolume.NewMounter initialization failed for volume "pvc-163365fd-7b78-4395-a947-1f43ffead322" : kubern │
│ etes.io/csi: expected valid fsGroupPolicy, received nil value or empty string    `

This is with Rook 1.5.4.
I've looked around all day for a fix this to issue, but I keep coming back to this thread.
Any help here would be greatly appreciated.

**Comment by jmarcedwards** [comment] 2020-12-21 20:29
I'm just trying to verify my Rook-Ceph installation following the instructions with the mysql & wordpress examples that are in the repo at rook/cluster/examples/kubernetes.

**Comment by andyzhangx** [comment] 2020-12-22 02:15
the error(`etes.io/csi: expected valid fsGroupPolicy, received nil value or empty string`) happened here:
https://github.com/kubernetes/kubernetes/blob/6d5cb36d36f34cb4f5735b6adcd5ea8ebb4440ba/pkg/volume/csi/csi_plugin.go#L910-L913

@huffmanca looks like this is a backward-compatibility issue, if `csiDriver.Spec.FSGroupPolicy` is not specified in k8s 1.20, what about `return storage.ReadWriteOnceWithFSTypeFSGroupPolicy, nil` by default?

@jmarcedwards one workaround is disable CSIVolumeFSGroupPolicy in kubelet by `--feature-gates=CSIVolumeFSGroupPolicy=false`

**Comment by SomKen** [comment] 2021-01-16 09:02
> 
> 
> the error(`etes.io/csi: expected valid fsGroupPolicy, received nil value or empty string`) happened here:
> https://github.com/kubernetes/kubernetes/blob/6d5cb36d36f34cb4f5735b6adcd5ea8ebb4440ba/pkg/volume/csi/csi_plugin.go#L910-L913
> 
> @huffmanca looks like this is a backward-compatibility issue, if `csiDriver.Spec.FSGroupPolicy` is not specified in k8s 1.20, what about `return storage.ReadWriteOnceWithFSTypeFSGroupPolicy, nil` by default?
> 
> @jmarcedwards one workaround is disable CSIVolumeFSGroupPolicy in kubelet by `--feature-gates=CSIVolumeFSGroupPolicy=false`

Thanks! This totally unblocked me from my CSI issues. Thanks!

**Comment by jmarcedwards** [comment] 2021-01-20 16:38
> > the error(`etes.io/csi: expected valid fsGroupPolicy, received nil value or empty string`) happened here:
> > https://github.com/kubernetes/kubernetes/blob/6d5cb36d36f34cb4f5735b6adcd5ea8ebb4440ba/pkg/volume/csi/csi_plugin.go#L910-L913
> > @huffmanca looks like this is a backward-compatibility issue, if `csiDriver.Spec.FSGroupPolicy` is not specified in k8s 1.20, what about `return storage.ReadWriteOnceWithFSTypeFSGroupPolicy, nil` by default?
> > @jmarcedwards one workaround is disable CSIVolumeFSGroupPolicy in kubelet by `--feature-gates=CSIVolumeFSGroupPolicy=false`
> 
> Thanks! This totally unblocked me from my CSI issues. Thanks!

Did it work for you to disable the CSIVolumeFSGroupPolicy with the --feature-gates?  How do you set this on the kubelet with kubectl?

Thanks, Marc

**Comment by SomKen** [comment] 2021-01-20 17:09
> 
> 
> > > the error(`etes.io/csi: expected valid fsGroupPolicy, received nil value or empty string`) happened here:
> > > https://github.com/kubernetes/kubernetes/blob/6d5cb36d36f34cb4f5735b6adcd5ea8ebb4440ba/pkg/volume/csi/csi_plugin.go#L910-L913
> > > @huffmanca looks like this is a backward-compatibility issue, if `csiDriver.Spec.FSGroupPolicy` is not specified in k8s 1.20, what about `return storage.ReadWriteOnceWithFSTypeFSGroupPolicy, nil` by default?
> > > @jmarcedwards one workaround is disable CSIVolumeFSGroupPolicy in kubelet by `--feature-gates=CSIVolumeFSGroupPolicy=false`
> > 
> > 
> > Thanks! This totally unblocked me from my CSI issues. Thanks!
> 
> Did it work for you to disable the CSIVolumeFSGroupPolicy with the --feature-gates? How do you set this on the kubelet with kubectl?
> 
> Thanks, Marc

I added `--feature-gates=CSIVolumeFSGroupPolicy=false` to the end `ExecStart=` of in /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

**Comment by SomKen** [comment] 2021-01-24 17:58
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Looks like it was disabled by default in 1.19 but is enabled in 1.20.

**Comment by kvaps** [comment] 2021-03-16 16:32
I also faced with such problem on [linstor-csi](https://github.com/piraeusdatastore/linstor-csi) driver.

Setting `fsGroupPolicy: None` as suggested @andyzhangx in https://github.com/kubernetes-csi/csi-driver-smb/issues/176#issuecomment-748477711 does not helping much.

It seems setting `--feature-gates=CSIVolumeFSGroupPolicy=false` is reliable workaround for kubelets, but how to fix it for proper way?

**Comment by SomKen** [comment] 2021-03-16 17:53
> 
> 
> I also faced with such problem on [linstor-csi](https://github.com/piraeusdatastore/linstor-csi) driver.
> 
> Setting `fsGroupPolicy: None` as suggested @andyzhangx in [#176 (comment)](https://github.com/kubernetes-csi/csi-driver-smb/issues/176#issuecomment-748477711) does not helping much.
> 
> It seems setting `--feature-gates=CSIVolumeFSGroupPolicy=false` is reliable workaround for kubelets, but how to fix it for proper way?

Updating your deployments? https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/ It seems this isn't "broken" as this feature is now enabled vs disabled in previous versions. Either manually disable the policy or update your deployments seems to be the only options.

**Comment by SomKen** [comment] 2021-03-16 17:54
@woloss Can you close this?

**Comment by andyzhangx** [comment] 2021-03-17 03:04
let me start an e2e test with 1.20

**Comment by andyzhangx** [comment] 2021-03-17 08:55
interesting thing is I have set up e2e test on Ubuntu 18.04 node with k8s 1.20.2 version, it only set following feature-gate, and e2e tests work well: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-smb/199/pull-csi-driver-smb-e2e-vmss/1372084342230093824/build-log.txt
```
"--feature-gates": "PodPriority=true",
```

I think it could be related to `Ubuntu 20.04`, this driver is never tested on Ubuntu 20.04

**Closed** 2021-05-11 15:40 UTC
Labels: kind/bug

**Comment by maxisam** [comment] 2021-05-17 03:09
@woloss why do we close this? I thought it still has issue with ubuntu 20.04 + k8s 1.20.2

**Comment by SomKen** [comment] 2021-05-17 03:13
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  It's not an issue - it's a feature ;)                                                                                                                                                                                                                                                                                                                         From: ***@***.***Sent: May 16, 2021 20:09To: ***@***.***Reply-to: ***@***.***Cc: ***@***.***; ***@***.***Subject: Re: [kubernetes-csi/csi-driver-smb] could not mount SMB share in 1.20 (#176)  
@woloss why do we close this? I thought it still has issue with ubuntu 20.04 + k8s 1.20.2

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by woloss** [comment] 2021-05-20 12:13
> @woloss why do we close this? I thought it still has issue with ubuntu 20.04 + k8s 1.20.2

I didn't pay attention to issue. Plus, on brand new single node k8s or cluster, it's not an issue. Just tested with brand new 1.21 VM and it's working right away.

**Comment by devopstales** [comment] 2021-11-02 11:43
It seems the problem was caused by incompatibility of the versions kubelet v1.20 and apiservers v1.19.
